### ISSUE TITLE
Difficulties using the plugin

### ISSUE THREAD

**Issue by AllanGErnst** [DerBeutlin/ros.el#21]
This is not an issue but a cry for help.
I've asked this question on stack overflow (https://stackoverflow.com/questions/72521820/ros2-development-in-doom-emacs)
- If you have it in you, any help is appreciated :)
Thanks. BR

**Comment by DerBeutlin** [comment]
Hi,

the project would probably benefit from some more documentation, however I'm not sure if there are many users besides myself.

Regarding your questions:

The Hydra makes it easy to use all the different commands
I use 
``
(map! :leader :desc "ROS" "ρ" #'hydra-ros-main/body)
``

to map the hydra to <SPC>+ρ in my config, because in my keyboard layout ρ is an easy to to produce letter and p and P was already taken. You however probably want a different keybinding.

You should also set the variable `ros-workspaces` like in the following

``
  (setq ros-workspaces (list (ros-dump-workspace :tramp-prefix nil :workspace "~/git/catkin_ws" :extends '("/opt/ros/noetic/"))))
``

or add even more workspaces. 
The first one will be selected by default.
You can now start the hydra with the keybinding defined above and start different kind of actions (mostly build actions).
E.g. 
``
<SPC>+ρ -> c -> w
``

builds the currently selected workspace. 
You can select multiple compile options and also save the defaults using the transient library.

This plugin only supports buiilding ROS workspaces with colcon, since that way I don't need to implement different commands for ROS1 and ROS2.

If you have more questions or feature requests, feel free to reach out.
I doubt that you will find much help in stackoverflow for this specific package because I doubt many people use it. Maybe link to this answer and mark the question as answered.

**Comment by AllanGErnst** [comment]
> Hi,
> 
> the project would probably benefit from some more documentation, however I'm not sure if there are many users besides myself.
> 
> Regarding your questions:
> 
> The Hydra makes it easy to use all the different commands I use `(map! :leader :desc "ROS" "ρ" #'hydra-ros-main/body)`
> 
> to map the hydra to +ρ in my config, because in my keyboard layout ρ is an easy to to produce letter and p and P was already taken. You however probably want a different keybinding.
> 
> You should also set the variable `ros-workspaces` like in the following
> 
> `(setq ros-workspaces (list (ros-dump-workspace :tramp-prefix nil :workspace "~/git/catkin_ws" :extends '("/opt/ros/noetic/"))))`
> 
> or add even more workspaces. The first one will be selected by default. You can now start the hydra with the keybinding defined above and start different kind of actions (mostly build actions). E.g. `<SPC>+ρ -> c -> w`
> 
> builds the currently selected workspace. You can select multiple compile options and also save the defaults using the transient library.
> 
> This plugin only supports buiilding ROS workspaces with colcon, since that way I don't need to implement different commands for ROS1 and ROS2.
> 
> If you have more questions or feature requests, feel free to reach out. I doubt that you will find much help in stackoverflow for this specific package because I doubt many people use it. Maybe link to this answer and mark the question as answered.

Thank you very much for your answer.
I've not really progressed that much since last time.

I have the following in my packages.el:
```
(package! ros
  :recipe (:host github
           :repo "DerBeutlin/ros.el"))
;; =ros.el=:1 ends here
```

and this in config.el:
```
(use-package! ros
  :init (map! :leader
              :prefix ("l" . "custom")
              :desc "Hydra ROS" "r" #'hydra-ros-main/body)
  :commands (hydra-ros-main/body ros-set-workspace)
  :config
  (setq ros-workspaces
        (list (ros-dump-workspace :tramp-prefix nil :workspace "~/ros2_ws" :extends '("/opt/ros/foxy/"))
              (ros-dump-workspace :tramp-prefix nil :workspace "~/overlay_ws" :extends '("/opt/ros/foxy/" "~/ros2_ws/install")))))
```

But when I open a project within the workspace with Neotree, say ~/ros2_ws/scr/my_awesome_package, it can't find #include "rclcpp/rclcpp.hpp" and it's complaining about `Too many errors emitted, stopping now [fatal_too_many_errors].`

Also when trying to launch Hydra (SPC-l-r), it gives me `Cannot open load file: No such file or directory, kv`

Any ideas? :)

Thanks,
BR. Allan

**Comment by DerBeutlin** [comment]
Are you able to build your workspace normally outside Emacs in the terminal? If not than this is not the correct place for your problem because I'm also just calling ``colcon`` commands,
If you can then this plugin should print in the first line of the compile window, the command that it is actually running.
Can you paste it here? Can you run this one successfully in your terminal?

**Comment by AllanGErnst** [comment]
Yes - I've no problem running colcon build from the terminal.

And I just found out that LSP requires a `compile_commands.json` to get the include paths - including /opt/ros/foxy/include.
This I exported using `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .` in scr/my_pkg. However it generates a ton of stuff so I had to write a script to remove the rest.

So now ready to test your stuff :)
